/********************************************************************************/
/********************************************************************************/
/*****************       Aathur:Shehab Ahmed Ragaai          ********************/
/*****************       Layer:MCAL                          ********************/
/*****************       SWC:PORT                            ********************/
/*****************       version:1.00                        ********************/
/********************************************************************************/
/********************************************************************************/

#ifndef PORT_PRIVATE_H_
#define PORT_PRIVATE_H_

#define PORT_CONC(P7,P6,P5,P4,P3,P2,P1,P0)            PORT_CONC_HELPER(P7,P6,P5,P4,P3,P2,P1,P0)

#define PORT_CONC_HELPER(P7,P6,P5,P4,P3,P2,P1,P0)     0b##P7##P6##P5##P4##P3##P2##P1##P0

                

#define PORTA_DIR   PORT_CONC(DIO_PORTA_PIN7_DIR,DIO_PORTA_PIN6_DIR,DIO_PORTA_PIN5_DIR,DIO_PORTA_PIN4_DIR,DIO_PORTA_PIN3_DIR,DIO_PORTA_PIN2_DIR,DIO_PORTA_PIN1_DIR,DIO_PORTA_PIN0_DIR)

#define PORTB_DIR   PORT_CONC(DIO_PORTB_PIN7_DIR,DIO_PORTB_PIN6_DIR,DIO_PORTB_PIN5_DIR,DIO_PORTB_PIN4_DIR,DIO_PORTB_PIN3_DIR,DIO_PORTB_PIN2_DIR,DIO_PORTB_PIN1_DIR,DIO_PORTB_PIN0_DIR) 

#define PORTC_DIR   PORT_CONC(DIO_PORTC_PIN7_DIR,DIO_PORTC_PIN6_DIR,DIO_PORTC_PIN5_DIR,DIO_PORTC_PIN4_DIR,DIO_PORTC_PIN3_DIR,DIO_PORTC_PIN2_DIR,DIO_PORTC_PIN1_DIR,DIO_PORTC_PIN0_DIR) 

#define PORTD_DIR   PORT_CONC(DIO_PORTD_PIN7_DIR,DIO_PORTD_PIN6_DIR,DIO_PORTD_PIN5_DIR,DIO_PORTD_PIN4_DIR,DIO_PORTD_PIN3_DIR,DIO_PORTD_PIN2_DIR,DIO_PORTD_PIN1_DIR,DIO_PORTD_PIN0_DIR)

#define PORTE_DIR   PORT_CONC(DIO_PORTE_PIN7_DIR,DIO_PORTE_PIN6_DIR,DIO_PORTE_PIN5_DIR,DIO_PORTE_PIN4_DIR,DIO_PORTE_PIN3_DIR,DIO_PORTE_PIN2_DIR,DIO_PORTE_PIN1_DIR,DIO_PORTE_PIN0_DIR) 

#define PORTF_DIR   PORT_CONC(DIO_PORTF_PIN7_DIR,DIO_PORTF_PIN6_DIR,DIO_PORTF_PIN5_DIR,DIO_PORTF_PIN4_DIR,DIO_PORTF_PIN3_DIR,DIO_PORTF_PIN2_DIR,DIO_PORTF_PIN1_DIR,DIO_PORTF_PIN0_DIR) 

#define PORTG_DIR   PORT_CONC(0,0,0,DIO_PORTG_PIN4_DIR,DIO_PORTG_PIN3_DIR,DIO_PORTG_PIN2_DIR,DIO_PORTG_PIN1_DIR,DIO_PORTG_PIN0_DIR)



#define PORTA_INTL   PORT_CONC(DIO_PORTA_PIN7_INTI_VALUE,DIO_PORTA_PIN6_INTI_VALUE,DIO_PORTA_PIN5_INTI_VALUE,DIO_PORTA_PIN4_INTI_VALUE,DIO_PORTA_PIN3_INTI_VALUE,DIO_PORTA_PIN2_INTI_VALUE,DIO_PORTA_PIN1_INTI_VALUE,DIO_PORTA_PIN0_INTI_VALUE)

#define PORTB_INTL   PORT_CONC(DIO_PORTB_PIN7_INTI_VALUE,DIO_PORTB_PIN6_INTI_VALUE,DIO_PORTB_PIN5_INTI_VALUE,DIO_PORTB_PIN4_INTI_VALUE,DIO_PORTB_PIN3_INTI_VALUE,DIO_PORTB_PIN2_INTI_VALUE,DIO_PORTB_PIN1_INTI_VALUE,DIO_PORTB_PIN0_INTI_VALUE)

#define PORTC_INTL   PORT_CONC(DIO_PORTC_PIN7_INTI_VALUE,DIO_PORTC_PIN6_INTI_VALUE,DIO_PORTC_PIN5_INTI_VALUE,DIO_PORTC_PIN4_INTI_VALUE,DIO_PORTC_PIN3_INTI_VALUE,DIO_PORTC_PIN2_INTI_VALUE,DIO_PORTC_PIN1_INTI_VALUE,DIO_PORTC_PIN0_INTI_VALUE)

#define PORTD_INTL   PORT_CONC(DIO_PORTD_PIN7_INTI_VALUE,DIO_PORTD_PIN6_INTI_VALUE,DIO_PORTD_PIN5_INTI_VALUE,DIO_PORTD_PIN4_INTI_VALUE,DIO_PORTD_PIN3_INTI_VALUE,DIO_PORTD_PIN2_INTI_VALUE,DIO_PORTD_PIN1_INTI_VALUE,DIO_PORTD_PIN0_INTI_VALUE)

#define PORTE_INTL   PORT_CONC(DIO_PORTE_PIN7_INTI_VALUE,DIO_PORTE_PIN6_INTI_VALUE,DIO_PORTE_PIN5_INTI_VALUE,DIO_PORTE_PIN4_INTI_VALUE,DIO_PORTE_PIN3_INTI_VALUE,DIO_PORTE_PIN2_INTI_VALUE,DIO_PORTE_PIN1_INTI_VALUE,DIO_PORTE_PIN0_INTI_VALUE)

#define PORTF_INTL   PORT_CONC(DIO_PORTF_PIN7_INTI_VALUE,DIO_PORTF_PIN6_INTI_VALUE,DIO_PORTF_PIN5_INTI_VALUE,DIO_PORTF_PIN4_INTI_VALUE,DIO_PORTF_PIN3_INTI_VALUE,DIO_PORTF_PIN2_INTI_VALUE,DIO_PORTF_PIN1_INTI_VALUE,DIO_PORTF_PIN0_INTI_VALUE)

#define PORTG_INTL   PORT_CONC(0,0,0,DIO_PORTG_PIN4_INTI_VALUE,DIO_PORTG_PIN3_INTI_VALUE,DIO_PORTG_PIN2_INTI_VALUE,DIO_PORTG_PIN1_INTI_VALUE,DIO_PORTG_PIN0_INTI_VALUE)









#endif
