

#include "STD_TYPES.h"
#include "BIT_MATH.h"
#include "Timers_register.h"
#include "Timers_private.h"
#include "Timers_interface.h"
#include "Timers_config.h"
#include"DIO_interface.h"


/***********************************************Timer0****************************************************************************/

void Timer0_voidInit(void)
{
	/*Normal Timer operation*/
#if TIMER0_MODE==NORMAL
	CLEAR_BIT(TCCR0,TCCR0_WGM00);
	CLEAR_BIT(TCCR0,TCCR0_WGM01);


#elif TIMER0_MODE==PHASE_CORRECT_PWM
	SET_BIT(TCCR0,TCCR0_WGM00);
	CLEAR_BIT(TCCR0,TCCR0_WGM01);

#if  TIMER0_WAVE_FORM == COCWUSOCWD
	CLEAR_BIT(TCCR0,TCCR0_COM00);
	SET_BIT(TCCR0,TCCR0_COM01);

#elif TIMER0_WAVE_FORM == SOCWUCOCWD
	SET_BIT(TCCR0,TCCR0_COM00);
	SET_BIT(TCCR0,TCCR0_COM01);
#endif



#elif TIMER0_MODE==CTC
	CLEAR_BIT(TCCR0,TCCR0_WGM00);
	SET_BIT(TCCR0,TCCR0_WGM01);


#if TIMER0_WAVE_FORM == DISCONNECT
	CLEAR_BIT(TCCR0,TCCR0_COM00);
	CLEAR_BIT(TCCR0,TCCR0_COM01);
#elif TIMER0_WAVE_FORM == TOGGLE
	SET_BIT(TCCR0,TCCR0_COM00);
	CLEAR_BIT(TCCR0,TCCR0_COM01);
#elif TIMER0_WAVE_FORM == CLEAR
	CLEAR_BIT(TCCR0,TCCR0_COM00);
	SET_BIT(TCCR0,TCCR0_COM01);
#elif TIMER0_WAVE_FORM == SET
	SET_BIT(TCCR0,TCCR0_COM00);
	SET_BIT(TCCR0,TCCR0_COM01);

#endif


#elif TIMER0_MODE==FAST_PWM
	SET_BIT(TCCR0,TCCR0_WGM00);
	SET_BIT(TCCR0,TCCR0_WGM01);

#if  TIMER0_WAVE_FORM == COCSOT
	CLEAR_BIT(TCCR0,TCCR0_COM00);
	SET_BIT(TCCR0,TCCR0_COM01);

#elif TIMER0_WAVE_FORM == SOCCOT
	SET_BIT(TCCR0,TCCR0_COM00);
	SET_BIT(TCCR0,TCCR0_COM01);
#endif

#endif


#if TIMER0_PRE_SCALER == NO_PRESCALER
	SET_BIT(TCCR0,TCCR0_CS00);
	CLEAR_BIT(TCCR0,TCCR0_CS01);
	CLEAR_BIT(TCCR0,TCCR0_CS02);
#elif TIMER0_PRE_SCALER == TIMERS_PRESCALER_BY_8
	CLEAR_BIT(TCCR0,TCCR0_CS00);
	SET_BIT(TCCR0,TCCR0_CS01);
	CLEAR_BIT(TCCR0,TCCR0_CS02);
#elif TIMER0_PRE_SCALER == TIMERS_PRESCALER_BY_32
	SET_BIT(TCCR0,TCCR0_CS00);
	SET_BIT(TCCR0,TCCR0_CS01);
	CLEAR_BIT(TCCR0,TCCR0_CS02);
#elif TIMER0_PRE_SCALER == TIMERS_PRESCALER_BY_64
	CLEAR_BIT(TCCR0,TCCR0_CS00);
	CLEAR_BIT(TCCR0,TCCR0_CS01);
	SET_BIT(TCCR0,TCCR0_CS02);
#elif TIMER0_PRE_SCALER == TIMERS_PRESCALER_BY_128
	SET_BIT(TCCR0,TCCR0_CS00);
	CLEAR_BIT(TCCR0,TCCR0_CS01);
	SET_BIT(TCCR0,TCCR0_CS02);
#elif TIMER0_PRE_SCALER == TIMERS_PRESCALER_BY_256
	CLEAR_BIT(TCCR0,TCCR0_CS00);
	SET_BIT(TCCR0,TCCR0_CS01);
	SET_BIT(TCCR0,TCCR0_CS02);
#elif TIMER0_PRE_SCALER == TIMERS_PRESCALER_BY_1024
	SET_BIT(TCCR0,TCCR0_CS00);
	SET_BIT(TCCR0,TCCR0_CS01);
	SET_BIT(TCCR0,TCCR0_CS02);

#elif TIMER0_PRE_SCALER == TIMERS_EXTERNAL_CLOCK

	SET_BIT(ASSR,ASSR_AS0);
#endif


#if TIMER0_OVF_INTERRUPT == ENABLE
	SET_BIT(TIMSK,TIMSK_TOIE0);

#elif TIMER0_OVF_INTERRUPT == DISABLE

	CLEAR_BIT(TIMSK,TIMSK_TOIE0);
#endif

#if TIMER0_CTC_INTERRUPT == ENABLE
	SET_BIT(TIMSK,TIMSK_OCIE0);

#elif TIMER0_CTC_INTERRUPT == DISABLE

	CLEAR_BIT(TIMSK,TIMSK_OCIE0);
#endif

}

u8 Timer0_u8SetPreLoadValue(u8 Copy_u8CompareMatchValue)
{
	u8 Local_u8ErrorState=OK;
	if(Copy_u8CompareMatchValue<256)
	{
		TCNT0=Copy_u8CompareMatchValue;
	}
	else
	{
		Local_u8ErrorState=NOK;
	}
	return Local_u8ErrorState;

}
u8 Timer0_u8SetCompareMatchValue(u8 Copy_u8CompareMatchValue)
{
	u8 Local_u8ErrorState=OK;
	if(Copy_u8CompareMatchValue<256)
	{
		OCR0=Copy_u8CompareMatchValue;
	}
	else
	{
		Local_u8ErrorState=NOK;
	}
	return Local_u8ErrorState;

}


u8 Timer0_u8Timer0OVFCallBackFunc(void (*Copy_pvFunc)(void))
{
	u8 Local_u8ErrorState=OK;
	if(Copy_pvFunc!=NULL)
	{
		Global_pvFuncTimer0OVF=Copy_pvFunc;
	}
	else
	{
		Local_u8ErrorState=NOK;
	}
	return Local_u8ErrorState;
}
u8 Timer0_u8Timer0CTCCallBackFunc(void (*Copy_pvFunc)(void))
{
	u8 Local_u8ErrorState=OK;
	if(Copy_pvFunc!=NULL)
	{
		Global_pvFuncTimer0CTC=Copy_pvFunc;
	}
	else
	{
		Local_u8ErrorState=NOK;
	}
	return Local_u8ErrorState;
}

u8 Timer0_u8ReadTimerValue(void)
{
	return TCNT0;
}




void __vector_15 (void)
{
	Global_pvFuncTimer0CTC();
}
void __vector_16 (void)
{
	Global_pvFuncTimer0OVF();
}
/*End timer 0*/

/************************************************************************************************TIMER1*****************************************************************/

void TIMER1_voidInit(void)
{
#if  TIMER1_MODE==NORMAL
	CLEAR_BIT(TCCR1A,TCCR1A_WGM10 );
	CLEAR_BIT(TCCR1A,TCCR1A_WGM11);
	CLEAR_BIT(TCCR1B,TCCR1B_WGM12);
	CLEAR_BIT(TCCR1B,TCCR1B_WGM13);
#elif 	TIMER1_MODE==CTC
	CLEAR_BIT(TCCR1A,TCCR1A_WGM10 );
	CLEAR_BIT(TCCR1A,TCCR1A_WGM11);
	SET_BIT(TCCR1B,TCCR1B_WGM12);
	CLEAR_BIT(TCCR1B,TCCR1B_WGM13);

#elif TIMER1_MODE==PHASE_CORRECT_PWM_8BIT
	SET_BIT(TCCR1A,TCCR1A_WGM10);
	CLEAR_BIT(TCCR1A,TCCR1A_WGM11);
	CLEAR_BIT(TCCR1B,TCCR1B_WGM12);
	CLEAR_BIT(TCCR1B,TCCR1B_WGM13);

#elif TIMER1_MODE==PHASE_CORRECT_PWM_ICR

	CLAER_BIT(TCCR1A,TCCR1A_WGM10);
	SET_BIT(TCCR1A,TCCR1A_WGM11);
	CLEAR_BIT(TCCR1B,TCCR1B_WGM12);
	SET_BIT(TCCR1B,TCCR1B_WGM13);

#elif TIMER1_MODE==FAST_PWM_8BIT
	SET_BIT(TCCR1A,TCCR1A_WGM10 );
	CLEAR_BIT(TCCR1A,TCCR1A_WGM11);
	SET_BIT(TCCR1B,TCCR1B_WGM12);
	CLEAR_BIT(TCCR1B,TCCR1B_WGM13);
#elif 	TIMER1_MODE==FAST_PWM_ICR
	CLEAR_BIT(TCCR1A,TCCR1A_WGM10 );
	SET_BIT(TCCR1A,TCCR1A_WGM11);
	SET_BIT(TCCR1B,TCCR1B_WGM12);
	SET_BIT(TCCR1B,TCCR1B_WGM13);

#endif

#if TIMER1_CHANNELA==ENABLE
#if TIMER1_MODE==PHASE_CORRECT_PWM_8BIT||TIMER1_MODE==PHASE_CORRECT_PWM_ICR
#if TIMER1_WAVE_FORM_CHANNELA==DISCONNECT
	CLEAR_BIT(TCCR1A,TCCR1A_COM1A0);
	CLEAR_BIT(TCCR1A,TCCR1A_COM1A1);
#elif TIMER1_WAVE_FORM_CHANNELA==COCWUSOCWD
	CLEAR_BIT(TCCR1A,TCCR1A_COM1A0);
	SET_BIT(TCCR1A,TCCR1A_COM1A1);
#elif 	TIMER1_WAVE_FORM_CHANNELA==SOCWUCOCWD
	SET_BIT(TCCR1A,TCCR1A_COM1A0);
	SET_BIT(TCCR1A,TCCR1A_COM1A1);
#endif
#elif TIMER1_MODE==FAST_PWM_8BIT||TIMER1_MODE==FAST_PWM_ICR
#if TIMER1_WAVE_FORM_CHANNELA==DISCONNECT
	CLEAR_BIT(TCCR1A,TCCR1A_COM1A0);
	CLEAR_BIT(TCCR1A,TCCR1A_COM1A1);
#elif TIMER1_WAVE_FORM_CHANNELA==COCSOT
	CLEAR_BIT(TCCR1A,TCCR1A_COM1A0);
	SET_BIT(TCCR1A,TCCR1A_COM1A1);
#elif 	TIMER1_WAVE_FORM_CHANNELA==SOCCOT
	SET_BIT(TCCR1A,TCCR1A_COM1A0);
	SET_BIT(TCCR1A,TCCR1A_COM1A1);
#endif
#elif TIMER1_MODE==CTC
#if TIMER1_WAVE_FORM_CHANNELA==DISCONNECT
	CLEAR_BIT(TCCR1A,TCCR1A_COM1A0);
	CLEAR_BIT(TCCR1A,TCCR1A_COM1A1);
#elif TIMER1_WAVE_FORM_CHANNELA==SET
	SET_BIT(TCCR1A,TCCR1A_COM1A0);
	SET_BIT(TCCR1A,TCCR1A_COM1A1);

#elif TIMER1_WAVE_FORM_CHANNELA==CLEAR
	CLEAR_BIT(TCCR1A,TCCR1A_COM1A0);
	SET_BIT(TCCR1A,TCCR1A_COM1A1);
#elif 	TIMER1_WAVE_FORM_CHANNELA==TOGGEL
	SET_BIT(TCCR1A,TCCR1A_COM1A0);
	CLEAR_BIT(TCCR1A,TCCR1A_COM1A1);
#endif
#endif


#if TIMER1_CTC_CHANNELA_INTERRUPT==ENABLE
	SET_BIT(TIMSK,TIMSK_OCIE1A);
#elif TIMER1_CTC_CHANNELA_INTERRUPT==DISABLE
	CLEAR_BIT(TIMSK,TIMSK_OCIE1A);
#endif
#endif


#if TIMER1_CHANNELB==ENABLE

#if TIMER1_MODE==PHASE_CORRECT_PWM_8BIT||TIMER1_MODE==PHASE_CORRECT_PWM_ICR
#if TIMER1_WAVE_FORM_CHANNELB==DISCONNECT
	CLEAR_BIT(TCCR1A,TCCR1A_COM1B0);
	CLEAR_BIT(TCCR1A,TCCR1A_COM1B1);
#elif TIMER1_WAVE_FORM_CHANNELB==COCWUSOCWD
	CLEAR_BIT(TCCR1A,TCCR1A_COM1B0);
	SET_BIT(TCCR1A,TCCR1A_COM1B1);
#elif 	TIMER1_WAVE_FORM_CHANNELB==SOCWUCOCWD
	SET_BIT(TCCR1A,TCCR1A_COM1B0);
	SET_BIT(TCCR1A,TCCR1A_COM1B1);
#endif



#elif TIMER1_MODE==FAST_PWM_8BIT||TIMER1_MODE==FAST_PWM_ICR
#if TIMER1_WAVE_FORM_CHANNELB==DISCONNECT
	CLEAR_BIT(TCCR1A,TCCR1A_COM1B0);
	CLEAR_BIT(TCCR1A,TCCR1A_COM1B1);
#elif TIMER1_WAVE_FORM_CHANNELB==COCSOT
	CLEAR_BIT(TCCR1A,TCCR1A_COM1B0);
	SET_BIT(TCCR1A,TCCR1A_COM1B1);
#elif 	TIMER1_WAVE_FORM_CHANNELB==SOCCOT
	SET_BIT(TCCR1A,TCCR1A_COM1B0);
	SET_BIT(TCCR1A,TCCR1A_COM1B1);

#endif
#elif TIMER1_MODE==CTC
#if TIMER1_WAVE_FORM_CHANNELB==DISCONNECT
	CLEAR_BIT(TCCR1A,TCCR1A_COM1B0);
	CLEAR_BIT(TCCR1A,TCCR1A_COM1B1);
#elif TIMER1_WAVE_FORM_CHANNELB==SET
	SET_BIT(TCCR1A,TCCR1A_COM1B0);
	SET_BIT(TCCR1A,TCCR1A_COM1B1);

#elif TIMER1_WAVE_FORM_CHANNELB==CLEAR
	CLEAR_BIT(TCCR1A,TCCR1A_COM1B0);
	SET_BIT(TCCR1A,TCCR1A_COM1B1);
#elif 	TIMER1_WAVE_FORM_CHANNELB==TOGGEL
	SET_BIT(TCCR1A,TCCR1A_COM1B0);
	CLEAR_BIT(TCCR1A,TCCR1A_COM1B1);
#endif
#endif

#if TIMER1_CTC_CHANNELB_INTERRUPT==ENABLE
	SET_BIT(TIMSK,TIMSK_OCIE1B);
#elif TIMER1_CTC_CHANNELB_INTERRUPT==DISABLE
	CLEAR_BIT(TIMSK,TIMSK_OCIE1B);
#endif


#endif

#if TIMER1_CHANNELC==ENABLE
#if TIMER1_MODE==PHASE_CORRECT_PWM_8BIT||TIMER1_MODE==PHASE_CORRECT_PWM_ICR
#if TIMER1_WAVE_FORM_CHANNELC==DISCONNECT
	CLEAR_BIT(TCCR1A,TCCR1A_COM1C0);
	CLEAR_BIT(TCCR1A,TCCR1A_COM1C1);
#elif TIMER1_WAVE_FORM_CHANNELC==COCWUSOCWD
	CLEAR_BIT(TCCR1A,TCCR1A_COM1C0);
	SET_BIT(TCCR1A,TCCR1A_COM1C1);
#elif 	TIMER1_WAVE_FORM_CHANNELC==SOCWUCOCWD
	SET_BIT(TCCR1A,TCCR1A_COM1C0);
	SET_BIT(TCCR1A,TCCR1A_COM1C1);
#endif
#elif TIMER1_MODE==FAST_PWM_8BIT||TIMER1_MODE==FAST_PWM_ICR
#if TIMER1_WAVE_FORM_CHANNELC==DISCONNECT
	CLEAR_BIT(TCCR1A,TCCR1A_COM1C0);
	CLEAR_BIT(TCCR1A,TCCR1A_COM1C1);
#elif TIMER1_WAVE_FORM_CHANNELC==COCSOT
	CLEAR_BIT(TCCR1A,TCCR1A_COM1C0);
	SET_BIT(TCCR1A,TCCR1A_COM1C1);
#elif 	TIMER1_WAVE_FORM_CHANNELC==SOCCOT
	SET_BIT(TCCR1A,TCCR1A_COM1C0);
	SET_BIT(TCCR1A,TCCR1A_COM1C1);
#endif
#elif TIMER1_MODE==CTC
#if TIMER1_WAVE_FORM_CHANNELC==DISCONNECT
	CLEAR_BIT(TCCR1A,TCCR1A_COM1C0);
	CLEAR_BIT(TCCR1A,TCCR1A_COM1C1);
#elif TIMER1_WAVE_FORM_CHANNELC==SET
	SET_BIT(TCCR1A,TCCR1A_COM1C0);
	SET_BIT(TCCR1A,TCCR1A_COM1C1);

#elif TIMER1_WAVE_FORM_CHANNELC==CLEAR
	CLEAR_BIT(TCCR1A,TCCR1A_COM1C0);
	SET_BIT(TCCR1A,TCCR1A_COM1C1);
#elif 	TIMER1_WAVE_FORM_CHANNELC==TOGGEL
	SET_BIT(TCCR1A,TCCR1A_COM1C0);
	CLEAR_BIT(TCCR1A,TCCR1A_COM1C1);

#endif
#endif
#if TIMER1_CTC_CHANNELC_INTERRUPT==ENABLE
	SET_BIT(ETIMSK,ETIMSK_OCIE1C);
#elif TIMER1_CTC_CHANNELC_INTERRUPT==DISABLE
	CLEAR_BIT(ETIMSK,ETIMSK_OCIE1C);
#endif

#endif

	/*Timer1 PreScaler*/
#if TIMER1_PRESCALER==TIMERS_NO_PRESCALAR
	SET_BIT(TCCR1B,TCCR1B_CS10);
	CLEAR_BIT(TCCR1B,TCCR1B_CS11);
	CLEAR_BIT(TCCR1B,TCCR1B_CS12);
#elif TIMER1_PRESCALER==TIMERS_PRESCALAR_BY_8
	CLEAR_BIT(TCCR1B,TCCR1B_CS10);
	SET_BIT(TCCR1B,TCCR1B_CS11);
	CLEAR_BIT(TCCR1B,TCCR1B_CS12);
#elif TIMER1_PRESCALER==TIMERS_PRESCALAR_BY_64
	SET_BIT(TCCR1B,TCCR1B_CS10);
	SET_BIT(TCCR1B,TCCR1B_CS11);
	CLEAR_BIT(TCCR1B,TCCR1B_CS12);
#elif TIMER1_PRESCALER==TIMERS_PRESCALAR_BY_256
	CLEAR_BIT(TCCR1B,TCCR1B_CS10);
	CLEAR_BIT(TCCR1B,TCCR1B_CS11);
	SET_BIT(TCCR1B,TCCR1B_CS12);
#elif TIMER1_PRESCALER==TIMERS_PRESCALAR_BY_1024
	SET_BIT(TCCR1B,TCCR1B_CS10);
	CLEAR_BIT(TCCR1B,TCCR1B_CS11);
	SET_BIT(TCCR1B,TCCR1B_CS12);
#elif TIMER1_PRESCALER==TIMERS_EXTERNAL_CLOCK_FALLING
	CLEAR_BIT(TCCR1B,TCCR1B_CS10);
	SET_BIT(TCCR1B,TCCR1B_CS11);
	SET_BIT(TCCR1B,TCCR1B_CS12);
#elif TIMER1_PRESCALER==TIMERS_EXTERNAL_CLOCK_RISING
	SET_BIT(TCCR1B,TCCR1B_CS10);
	SET_BIT(TCCR1B,TCCR1B_CS11);
	SET_BIT(TCCR1B,TCCR1B_CS12);
#endif

	/*Over Flow Interrupt */
#if TIMER1_OVF_INTERRUPT==ENABLE
	SET_BIT(TIMSK,TIMSK_TOIE1);
#elif TIMER1_OVF_INTERRUPT==DISABLE
	CLEAR_BIT(TIMSK,TIMSK_TOIE1);
#endif

}

u8 TIMER1_u8SetCompareMatchValue(u8 Copy_u8Channel,u16 Copy_CTCValue)
{

	u8  Local_ErrorState=0;


	if(Copy_CTCValue<=65536&&Copy_u8Channel<=CHANNELC)
	{

		if(Copy_u8Channel==CHANNELA)
		{
			OCR1AH=(u8)(Copy_CTCValue>>8);
			OCR1AL=(u8)(Copy_CTCValue);


		}
		else if (Copy_u8Channel==CHANNELB)
		{
			OCR1BH=(u8)(Copy_CTCValue>>8);
			OCR1BL=(u8)(Copy_CTCValue);


		}
		else if (Copy_u8Channel==CHANNELC)
		{

			OCR1CH=(u8)(Copy_CTCValue>>8);
			OCR1CL=(u8)(Copy_CTCValue);
		}

	}

	else
	{
		Local_ErrorState=1;
	}

	return Local_ErrorState;
}

u8 TIMER1_u8SetICRValue(u16 Copy_ICR1Value)
{

	u8  Local_ErrorState=0;


	if(Copy_ICR1Value<=65536)
	{
		ICR1H=(u8)(Copy_ICR1Value>>8);
		ICR1L=(u8)(Copy_ICR1Value);
	}


	else
	{
		Local_ErrorState=1;
	}

	return Local_ErrorState;
}


u8 TIMER1_u8Timer1OVFCallBackFunc(void (*COPY_pvFuncTimer1OVF)(void))
{
	u8 Local_u8ErorState=0;
	if(COPY_pvFuncTimer1OVF!=NULL)
	{
		Global_pvFuncTimer1OVF=COPY_pvFuncTimer1OVF;
	}
	else
	{
		Local_u8ErorState=1;
	}

	return Local_u8ErorState;
}

u8 TIMER1_u8Timer1CTCCallBackFunc(u8 Copy_u8Channel,void(*COPY_pvFuncTimer1CTC)(void))
{
	u8 Local_u8ErorState=0;

	if(Copy_u8Channel<=CHANNELC&&COPY_pvFuncTimer1CTC!=NULL)
	{
		if(Copy_u8Channel==CHANNELA)
		{
			Global_pvFuncTimer1CTCChannelA=COPY_pvFuncTimer1CTC;
		}
		else if (Copy_u8Channel==CHANNELB)
		{
			Global_pvFuncTimer1CTCChannelB=COPY_pvFuncTimer1CTC;
		}
		else if (Copy_u8Channel==CHANNELC)
		{
			Global_pvFuncTimer1CTCChannelC=COPY_pvFuncTimer1CTC;
		}
	}
	else
	{
		Local_u8ErorState=1;
	}

	return Local_u8ErorState;
}




void __vector_12 (void)
{
	Global_pvFuncTimer1CTCChannelA();
}

void __vector_13 (void)
{
	Global_pvFuncTimer1CTCChannelB();
}
void __vector_14 (void)
{
	Global_pvFuncTimer1OVF();
}

void __vector_24 (void)
{
	Global_pvFuncTimer1CTCChannelC();
}
/*TIMER1 End*/

/****************************************************TIMER2*******************************************************************/
void TIMER2_voidInit(void)
{
	/*Timer2 Waveform Generation Mode*/
#if TIMER2_MODE==CTC
	CLEAR_BIT(TCCR2,TCCR2_WGM20);
	SET_BIT(TCCR2,TCCR2_WGM21);
#if TIMER2_WAVE_FORM == DISCONNECT
	CLEAR_BIT(TCCR2,TCCR2_COM20);
	CLEAR_BIT(TCCR2,TCCR2_COM21);
#elif TIMER2_WAVE_FORM==TOGGEL
	SET_BIT(TCCR2,TCCR2_COM20);
	CLEAR_BIT(TCCR2,TCCR2_COM21);
#elif TIMER2_WAVE_FORM==CLEAR
	CLEAR_BIT(TCCR2,TCCR2_COM20);
	SET_BIT(TCCR2,TCCR2_COM21);
#elif TIMER2_WAVE_FORM==SET
	SET_BIT(TCCR2,TCCR2_COM20);
	SET_BIT(TCCR2,TCCR2_COM21);
#endif



#elif 	TIMER2_MODE==FAST_PWM
	SET_BIT(TCCR2,TCCR2_WGM20);
	SET_BIT(TCCR2,TCCR2_WGM21);
#if TIMER2_WAVE_FORM==DISCONNECT
	CLEAR_BIT(TCCR2,TCCR2_COM20);
	CLEAR_BIT(TCCR2,TCCR2_COM21);
#elif TIMER2_WAVE_FORM==COCSOT
	CLEAR_BIT(TCCR2,TCCR2_COM20);
	SET_BIT(TCCR2,TCCR2_COM21);
#elif TIMER2_WAVE_FORM==SOCCOT
	SET_BIT(TCCR2,TCCR2_COM20);
	SET_BIT(TCCR2,TCCR2_COM21);
#endif

#elif  	TIMER2_MODE==PHASE_CORRECT_PWM
	SET_BIT(TCCR2,TCCR2_WGM20);
	CLEAR_BIT(TCCR2,TCCR2_WGM21);
#if TIMER2_WAVE_FORM==DISCONNECT
	CLEAR_BIT(TCCR2,TCCR2_COM20);
	CLEAR_BIT(TCCR2,TCCR2_COM21);
#elif TIMER2_WAVE_FORM==COCWUSOCWD
	CLEAR_BIT(TCCR2,TCCR2_COM20);
	SET_BIT(TCCR2,TCCR2_COM21);
#elif TIMER2_WAVE_FORM==SOCWUCOCWD
	SET_BIT(TCCR2,TCCR2_COM20);
	SET_BIT(TCCR2,TCCR2_COM21);
#endif

#elif  		TIMER2_MODE==NORMAL
	CLEAR_BIT(TCCR2,TCCR2_WGM20);
	CLEAR_BIT(TCCR2,TCCR2_WGM21);

#endif


	/*Timer2 PreScaler*/
#if TIMER2_PRESCALER==TIMERS_NO_PRESCALAR
	SET_BIT(TCCR2,TCCR2_CS20);
	CLEAR_BIT(TCCR2,TCCR2_CS21);
	CLEAR_BIT(TCCR2,TCCR2_CS22);
#elif TIMER2_PRESCALER==TIMERS_PRESCALAR_BY_8
	CLEAR_BIT(TCCR2,TCCR2_CS20);
	SET_BIT(TCCR2,TCCR2_CS21);
	CLEAR_BIT(TCCR2,TCCR2_CS22);
#elif TIMER2_PRESCALER==TIMERS_PRESCALAR_BY_64
	SET_BIT(TCCR2,TCCR2_CS20);
	SET_BIT(TCCR2,TCCR2_CS21);
	CLEAR_BIT(TCCR2,TCCR2_CS22);
#elif TIMER2_PRESCALER==TIMERS_PRESCALAR_BY_256
	CLEAR_BIT(TCCR2,TCCR2_CS20);
	CLEAR_BIT(TCCR2,TCCR2_CS21);
	SET_BIT(TCCR2,TCCR2_CS22);
#elif TIMER2_PRESCALER==TIMERS_PRESCALAR_BY_1024
	SET_BIT(TCCR2,TCCR2_CS20);
	CLEAR_BIT(TCCR2,TCCR2_CS21);
	SET_BIT(TCCR2,TCCR2_CS22);
#elif TIMER2_PRESCALER==TIMERS_EXTERNAL_CLOCK_FALLING
	CLEAR_BIT(TCCR2,TCCR2_CS20);
	SET_BIT(TCCR2,TCCR2_CS21);
	SET_BIT(TCCR2,TCCR2_CS22);
#elif TIMER2_PRESCALER==TIMERS_EXTERNAL_CLOCK_RISING
	SET_BIT(TCCR2,TCCR2_CS20);
	SET_BIT(TCCR2,TCCR2_CS21);
	SET_BIT(TCCR2,TCCR2_CS22);
#endif
	/*Over Flow Interrupt */
#if TIMER2_OVF_INTERRUPT==ENABLE
	SET_BIT(TIMSK,TIMSK_TOIE2);
#elif TIMER2_OVF_INTERRUPT==DISABLE
	CLEAR_BIT(TIMSK,TIMSK_TOIE2);
#endif

#if TIMER2_CTC_INTERRUPT==ENABLE
	SET_BIT(TIMSK,TIMSK_OCIE2);
#elif TIMER2_CTC_INTERRUPT==DISABLE
	CLEAR_BIT(TIMSK,TIMSK_OCIE2);
#endif

}

u8 TIMER2_u8Timer2OVFCallBackFunc(void (*COPY_pvFuncTimer2OVF)(void))
{
	u8 Local_u8ErorState=0;
	if(COPY_pvFuncTimer2OVF!=NULL)
	{
		Global_pvFuncTimer2OVF=COPY_pvFuncTimer2OVF;
	}
	else
	{
		Local_u8ErorState=1;
	}

	return Local_u8ErorState;
}

u8 TIMER2_u8Timer2CTCCallBackFunc(void (*COPY_pvFuncTimer2CTC)(void))
{
	u8 Local_u8ErorState=0;
	if(COPY_pvFuncTimer2CTC!=NULL)
	{
		Global_pvFuncTimer2CTC=COPY_pvFuncTimer2CTC;
	}
	else
	{
		Local_u8ErorState=1;
	}

	return Local_u8ErorState;
}

u8 TIMER2_u8SetCompareMatchValue(u8 Copy_CTCValue)
{
	u8  Local_ErrorState=0;
	if(Copy_CTCValue<=256)
	{
		OCR2=Copy_CTCValue;
	}
	else
	{
		Local_ErrorState=1;
	}

	return Local_ErrorState;
}

u8 TIMER2_u8SetOverFlowValue(u8 Copy_OVFValue)
{
	u8  Local_ErrorState=0;
	if(Copy_OVFValue<=256)
	{
		TCNT2=Copy_OVFValue;
	}
	else
	{
		Local_ErrorState=1;
	}

	return Local_ErrorState;
}

u8 TIMER2_u8TCNT2Read(void)
{


	return TCNT2;
}



void __vector_10 (void)
{
	Global_pvFuncTimer2OVF();
}

void __vector_9 (void)
{
	Global_pvFuncTimer2CTC();
}



/***********************************************Timer3****************************************************************************/

void TIMER3_voidInit(void)
{
#if TIMER3_MODE==NORMAL
	CLEAR_BIT(TCCR3B,TCCR3B_WGM33);
	CLEAR_BIT(TCCR3B,TCCR3B_WGM32);
	CLEAR_BIT(TCCR3A,TCCR3A_WGM31);
	CLEAR_BIT(TCCR3A,TCCR3A_WGM30);
#elif TIMER3_MODE==PHASE_CORRECT_PWM_8BIT
	CLEAR_BIT(TCCR3B,TCCR3B_WGM33);
	CLEAR_BIT(TCCR3B,TCCR3B_WGM32);
	CLEAR_BIT(TCCR3A,TCCR3A_WGM31);
	SET_BIT(TCCR3A,TCCR3A_WGM30);
#elif TIMER3_MODE == CTC
	CLEAR_BIT(TCCR3B,TCCR3B_WGM33);
	SET_BIT(TCCR3B,TCCR3B_WGM32);
	CLEAR_BIT(TCCR3A,TCCR3A_WGM31);
	CLEAR_BIT(TCCR3A,TCCR3A_WGM30);
#elif TIMER3_MODE== FAST_PWM_8BIT
	CLEAR_BIT(TCCR3B,TCCR3B_WGM33);
	SET_BIT(TCCR3B,TCCR3B_WGM32);
	CLEAR_BIT(TCCR3A,TCCR3A_WGM31);
	SET_BIT(TCCR3A,TCCR3A_WGM30);

#elif TIMER3_MODE == PHASE_CORRECT_PWM_ICR
	SET_BIT(TCCR3B,TCCR3B_WGM33);
	CLEAR_BIT(TCCR3B,TCCR3B_WGM32);
	SET_BIT(TCCR3A,TCCR3A_WGM31);
	CLEAR_BIT(TCCR3A,TCCR3A_WGM30);
#elif TIMER3_MODE == FAST_PWM_ICR
	SET_BIT(TCCR3B,TCCR3B_WGM33);
	SET_BIT(TCCR3B,TCCR3B_WGM32);
	SET_BIT(TCCR3A,TCCR3A_WGM31);
	CLEAR_BIT(TCCR3A,TCCR3A_WGM30);

#endif/*end for mode selection*/


	/*Channel A*/
#if TIMER3_CHANNELA == ENABLE
#if	TIMER3_MODE==FAST_PWM_8BIT||TIMER3_MODE==FAST_PWM_ICR

#if TIMER3_WAVE_FORM_CHANNELA ==DISCONNECT

	CLEAR_BIT(TCCR3A,TCCR3A_COM3A1);
	CLEAR_BIT(TCCR3A,TCCR3A_COM3A0);
#elif TIMER3_WAVE_FORM_CHANNELA  == TOGGLE

	CLEAR_BIT(TCCR3A,TCCR3A_COM3A1);
	SET_BIT(TCCR3A,TCCR3A_COM3A0);
#elif TIMER3_WAVE_FORM_CHANNELA  == COCSOT

	SET_BIT(TCCR3A,TCCR3A_COM3A1);
	CLEAR_BIT(TCCR3A,TCCR3A_COM3A0);
#elif TIMER3_WAVE_FORM_CHANNELA ==SOCCOT

	SET_BIT(TCCR3A,TCCR3A_COM3A1);
	SET_BIT(TCCR3A,TCCR3A_COM3A0);
#endif

#elif TIMER3_MODE==PHASE_CORRECT_PWM_8BIT||TIMER3_MODE==PHASE_CORRECT_PWM_ICR

#if TIMER3_WAVE_FORM_CHANNELA ==DISCONNECT
	CLEAR_BIT(TCCR3A,TCCR3A_COM3A1);
	CLEAR_BIT(TCCR3A,TCCR3A_COM3A0);
#elif TIMER3_WAVE_FORM_CHANNELA  == TOGGLE

	CLEAR_BIT(TCCR3A,TCCR3A_COM3A1);
	SET_BIT(TCCR3A,TCCR3A_COM3A0);
#elif TIMER3_WAVE_FORM_CHANNELA  == COCWUSOCWD

	SET_BIT(TCCR3A,TCCR3A_COM3A1);
	CLEAR_BIT(TCCR3A,TCCR3A_COM3A0);
#elif TIMER3_WAVE_FORM_CHANNELA ==SOCWUCOCWD

	SET_BIT(TCCR3A,TCCR3A_COM3A1);
	SET_BIT(TCCR3A,TCCR3A_COM3A0);
#endif

#elif TIMER3_MODE==CTC

#if TIMER3_WAVE_FORM_CHANNELA ==DISCONNECT
	CLEAR_BIT(TCCR3A,TCCR3A_COM3A1);
	CLEAR_BIT(TCCR3A,TCCR3A_COM3A0);
#elif TIMER3_WAVE_FORM == TOGGLE

	CLEAR_BIT(TCCR3A,TCCR3A_COM3A1);
	SET_BIT(TCCR3A,TCCR3A_COM3A0);
#elif TIMER3_WAVE_FORM_CHANNELA  == CLEAR

	SET_BIT(TCCR3A,TCCR3A_COM3A1);
	CLEAR_BIT(TCCR3A,TCCR3A_COM3A0);
#elif TIMER3_WAVE_FORM_CHANNELA ==SET

	SET_BIT(TCCR3A,TCCR3A_COM3A1);
	SET_BIT(TCCR3A,TCCR3A_COM3A0);
#endif
#endif


#if TIMER3_CTC_CHANNELA_INTERRUPT==ENABLE
	SET_BIT(ETIMSK,ETIMSK_OCIE3A);
#elif TIMER3_CTC_CHANNELA_INTERRUPT == DISABLE
	CLEAR_BIT(ETIMSK,ETIMSK_OCIE3A);
#endif
#endif/*End if for channel A options*/


	/*Channel B*/
#if TIMER3_CHANNELB == ENABLE
#if	TIMER3_MODE==FAST_PWM_8BIT||TIMER3_MODE==FAST_PWM_ICR

#if TIMER3_WAVE_FORM_CHANNELB==DISCONNECT

	CLEAR_BIT(TCCR3A,TCCR3A_COM3B1);
	CLEAR_BIT(TCCR3A,TCCR3A_COM3B0);
#elif TIMER3_WAVE_FORM_CHANNELB == TOGGLE

	CLEAR_BIT(TCCR3A,TCCR3A_COM3B1);
	SET_BIT(TCCR3A,TCCR3A_COM3B0);
#elif TIMER3_WAVE_FORM_CHANNELB == COCSOT

	SET_BIT(TCCR3A,TCCR3A_COM3B1);
	CLEAR_BIT(TCCR3A,TCCR3A_COM3B0);
#elif TIMER3_WAVE_FORM_CHANNELB==SOCCOT

	SET_BIT(TCCR3A,TCCR3A_COM3B1);
	SET_BIT(TCCR3A,TCCR3A_COM3B0);
#endif

#elif TIMER3_MODE==PHASE_CORRECT_PWM_8BIT||TIMER3_MODE==PHASE_CORRECT_PWM_ICR

#if TIMER3_WAVE_FORM_CHANNELB==DISCONNECT
	CLEAR_BIT(TCCR3A,TCCR3A_COM3B1);
	CLEAR_BIT(TCCR3A,TCCR3A_COM3B0);
#elif TIMER3_WAVE_FORM_CHANNELB == TOGGLE

	CLEAR_BIT(TCCR3A,TCCR3A_COM3B1);
	SET_BIT(TCCR3A,TCCR3A_COM3B0);
#elif TIMER3_WAVE_FORM_CHANNELB == COCWUSOCWD

	SET_BIT(TCCR3A,TCCR3A_COM3B1);
	CLEAR_BIT(TCCR3A,TCCR3A_COM3B0);
#elif TIMER3_WAVE_FORM_CHANNELB==SOCWUCOCWD

	SET_BIT(TCCR3A,TCCR3A_COM3B1);
	SET_BIT(TCCR3A,TCCR3A_COM3B0);
#endif

#elif TIMER3_MODE==CTC

#if TIMER3_WAVE_FORM_CHANNELB==DISCONNECT
	CLEAR_BIT(TCCR3A,TCCR3A_COM3B1);
	CLEAR_BIT(TCCR3A,TCCR3A_COM3B0);
#elif TIMER3_WAVE_FORM_CHANNELB == TOGGLE

	CLEAR_BIT(TCCR3A,TCCR3A_COM3B1);
	SET_BIT(TCCR3A,TCCR3A_COM3B0);
#elif TIMER3_WAVE_FORM_CHANNELB == CLEAR

	SET_BIT(TCCR3A,TCCR3A_COM3B1);
	CLEAR_BIT(TCCR3A,TCCR3A_COM3B0);
#elif TIMER3_WAVE_FORM_CHANNELB==SET

	SET_BIT(TCCR3A,TCCR3A_COM3B1);
	SET_BIT(TCCR3A,TCCR3A_COM3B0);
#endif
#endif


#if TIMER3_CTC_CHANNELB_INTERRUPT==ENABLE
	SET_BIT(ETIMSK,ETIMSK_OCIE3B);
#elif TIMER3_CTC_CHANNELB_INTERRUPT== DISABLE
	CLEAR_BIT(ETIMSK,ETIMSK_OCIE3B);
#endif
#endif/*End if for channel B options*/


	/*Channel C*/
#if TIMER3_CHANNELC == ENABLE
#if	TIMER3_MODE==FAST_PWM_8BIT||TIMER3_MODE==FAST_PWM_ICR

#if TIMER3_WAVE_FORM_CHANNELC==DISCONNECT

	CLEAR_BIT(TCCR3A,TCCR3A_COM3C1);
	CLEAR_BIT(TCCR3A,TCCR3A_COM3C0);
#elif TIMER3_WAVE_FORM_CHANNELC == TOGGLE

	CLEAR_BIT(TCCR3A,TCCR3A_COM3C1);
	SET_BIT(TCCR3A,TCCR3A_COM3C0);
#elif TIMER3_WAVE_FORM_CHANNELC== COCSOT

	SET_BIT(TCCR3A,TCCR3A_COM3C1);
	CLEAR_BIT(TCCR3A,TCCR3A_COM3C0);
#elif TIMER3_WAVE_FORM_CHANNELC==SOCCOT

	SET_BIT(TCCR3A,TCCR3A_COM3C1);
	SET_BIT(TCCR3A,TCCR3A_COM3C0);
#endif

#elif TIMER3_MODE==PHASE_CORRECT_PWM_8BIT||TIMER3_MODE==PHASE_CORRECT_PWM_ICR

#if TIMER3_WAVE_FORM_CHANNELC==DISCONNECT
	CLEAR_BIT(TCCR3A,TCCR3A_COM3C1);
	CLEAR_BIT(TCCR3A,TCCR3A_COM3C0);
#elif TIMER3_WAVE_FORM_CHANNELC == TOGGLE

	CLEAR_BIT(TCCR3A,TCCR3A_COM3C1);
	SET_BIT(TCCR3A,TCCR3A_COM3C0);
#elif TIMER3_WAVE_FORM_CHANNELC == COCWUSOCWD

	SET_BIT(TCCR3A,TCCR3A_COM3C1);
	CLEAR_BIT(TCCR3A,TCCR3A_COM3C0);
#elif TIMER3_WAVE_FORM_CHANNELC==SOCWUCOCWD

	SET_BIT(TCCR3A,TCCR3A_COM3C1);
	SET_BIT(TCCR3A,TCCR3A_COM3C0);
#endif

#elif TIMER3_MODE==CTC

#if TIMER3_WAVE_FORM_CHANNELC==DISCONNECT
	CLEAR_BIT(TCCR3A,TCCR3A_COM3C1);
	CLEAR_BIT(TCCR3A,TCCR3A_COM3C0);
#elif TIMER3_WAVE_FORM_CHANNELC== TOGGLE

	CLEAR_BIT(TCCR3A,TCCR3A_COM3C1);
	SET_BIT(TCCR3A,TCCR3A_COM3C0);
#elif TIMER3_WAVE_FORM_CHANNELC == CLEAR

	SET_BIT(TCCR3A,TCCR3A_COM3C1);
	CLEAR_BIT(TCCR3A,TCCR3A_COM3C0);
#elif TIMER3_WAVE_FORM_CHANNELC==SET

	SET_BIT(TCCR3A,TCCR3A_COM3C1);
	SET_BIT(TCCR3A,TCCR3A_COM3C0);
#endif
#endif


#if TIMER3_CTC_CHANNELC_INTERRUPT==ENABLE
	SET_BIT(ETIMSK,ETIMSK_OCIE3C);
#elif TIMER3_CTC_CHANNELC_INTERRUPT==DISABLE
	CLEAR_BIT(ETIMSK,ETIMSK_OCIE3C);
#endif
#endif/*End if for channel C options*/
	/*OVER FLOW INTERRUPT*/
#if TIMER3_OVF_INTERRUPT==ENABLE
	SET_BIT(ETIMSK,ETIMSK_TOIE3);
#endif

	/*PRESCALER SELECTION*/
#if TIMER3_PRE_SCALER==TIMERS_NO_PRESCALAR
	CLEAR_BIT(TCCR3B,TCCR3B_CS32);
	CLEAR_BIT(TCCR3B,TCCR3B_CS31);
	SET_BIT(TCCR3B,TCCR3B_CS30);
#elif TIMER3_PRE_SCALER == TIMERS_PRESCALER_BY_8
	CLEAR_BIT(TCCR3B,TCCR3B_CS32);
	SET_BIT(TCCR3B,TCCR3B_CS31);
	CLEAR_BIT(TCCR3B,TCCR3B_CS30);
#elif TIMER3_PRE_SCALER== TIMERS_PRESCALER_BY_64
	CLEAR_BIT(TCCR3B,TCCR3B_CS32);
	SET_BIT(TCCR3B,TCCR3B_CS31);
	SET_BIT(TCCR3B,TCCR3B_CS30);
#elif TIMER3_PRE_SCALER == TIMERS_PRESCALER_BY_256
	SET_BIT(TCCR3B,TCCR3B_CS32);
	CLEAR_BIT(TCCR3B,TCCR3B_CS31);
	CLEAR_BIT(TCCR3B,TCCR3B_CS30);
#elif TIMER3_PRE_SCALER == TIMERS_PRESCALER_BY_1024
	SET_BIT(TCCR3B,TCCR3B_CS32);
	CLEAR_BIT(TCCR3B,TCCR3B_CS31);
	SET_BIT(TCCR3B,TCCR3B_CS30);
#elif TIMER3_PRE_SCALER == TIMERS_EXTERNAL_CLOCK_FALLING
	SET_BIT(TCCR3B,TCCR3B_CS32);
	SET_BIT(TCCR3B,TCCR3B_CS31);
	CLEAR_BIT(TCCR3B,TCCR3B_CS30);
#elif TIMER3_PRE_SCALER == TIMERS_EXTERNAL_CLOCK_RISING
	SET_BIT(TCCR3B,TCCR3B_CS32);
	SET_BIT(TCCR3B,TCCR3B_CS31);
	SET_BIT(TCCR3B,TCCR3B_CS30);
#endif
}

u8 TIMER3_u8SetCompareMatchValue(u8 Copy_u8Channel,u16 Copy_CTCValue)
{

	u8 Local_u8ErrorState=0;

	if(Copy_CTCValue<=65535&&Copy_u8Channel<=CHANNELC)
	{

		switch(Copy_u8Channel)
		{
		case CHANNELA:
			OCR3AH=(u8)(Copy_CTCValue>>8);
			OCR3AL=(u8) (Copy_CTCValue);

			break;
		case CHANNELB:
			OCR3BH=(u8)(Copy_CTCValue>>8);
			OCR3BL=(u8) (Copy_CTCValue);

			break;
		case CHANNELC:
			OCR3CH=(u8)(Copy_CTCValue>>8);
			OCR3CL=(u8) (Copy_CTCValue);
			break;
		default :
			/*do nothing*/
			break;
		}
	}
	else
	{
		Local_u8ErrorState=1;
	}
	return Local_u8ErrorState;


}

u8 TIMER3_u8SetICRValue(u16 Copy_u16ICR3Value)
{
	u8 Local_u8ErrorState=0;
	if(Copy_u16ICR3Value<=65535)
	{
		ICR3H=(u8)(Copy_u16ICR3Value>>8);
		ICR3L=(u8)(Copy_u16ICR3Value);
	}
	else
	{
		Local_u8ErrorState=1;
	}

	return Local_u8ErrorState;

}

u8 TIMER3_u8Timer3OVFCallBackFunc(void (*COPY_pvFuncTimer3OVF)(void))
{
	u8 Local_u8ErrorState=0;
	if(COPY_pvFuncTimer3OVF!=NULL)
	{
		Global_pvFuncTimer3OVF=COPY_pvFuncTimer3OVF;
	}
	else
	{
		Local_u8ErrorState=1;
	}
	return Local_u8ErrorState;
}

u8 TIMER3_u8Timer3CTCCallBackFunc(u8 Copy_u8Channel,void(*COPY_pvFuncTimer3CTC)(void))
{
	u8 Local_u8ErrorState=0;
	if(Copy_u8Channel<=CHANNELC&&COPY_pvFuncTimer3CTC!=NULL)
	{
		switch(Copy_u8Channel)
		{
		case CHANNELA:
			Global_pvFuncTimer3CTCChannelA=COPY_pvFuncTimer3CTC;
			break;
		case CHANNELB:
			Global_pvFuncTimer3CTCChannelB=COPY_pvFuncTimer3CTC;
			break;
		case CHANNELC:
			Global_pvFuncTimer3CTCChannelC=COPY_pvFuncTimer3CTC;
			break;
		default:
			/*Do nothing*/
			break;
		}
	}
	else
	{
		Local_u8ErrorState=1;
	}
	return Local_u8ErrorState;
}

void __vector_26 (void)
{
	Global_pvFuncTimer3CTCChannelA();
}
void __vector_27 (void)
{
	Global_pvFuncTimer3CTCChannelB();
}
void __vector_28 (void)
{
	Global_pvFuncTimer3CTCChannelC();
}
void __vector_29 (void)
{
	Global_pvFuncTimer3OVF();
}


/*end timer 3*/

